gdjs.LoadingCode = {};
gdjs.LoadingCode.localVariables = [];
gdjs.LoadingCode.idToCallbackMap = new Map();
gdjs.LoadingCode.GDBackgroundObjects1= [];
gdjs.LoadingCode.GDBackgroundObjects2= [];
gdjs.LoadingCode.GDlogoObjects1= [];
gdjs.LoadingCode.GDlogoObjects2= [];
gdjs.LoadingCode.GDLoadingBarObjects1= [];
gdjs.LoadingCode.GDLoadingBarObjects2= [];
gdjs.LoadingCode.GDLoadingTextObjects1= [];
gdjs.LoadingCode.GDLoadingTextObjects2= [];
gdjs.LoadingCode.GDLoadingTipObjects1= [];
gdjs.LoadingCode.GDLoadingTipObjects2= [];
gdjs.LoadingCode.GDReplaySpriteObjects1= [];
gdjs.LoadingCode.GDReplaySpriteObjects2= [];


gdjs.LoadingCode.userFunc0x1a244b0 = function GDJSInlineCode(runtimeScene, objects) {
"use strict";

const loadingBar = runtimeScene.getScene().getVariables().get('LoadingBarTarget');

const imageURLs = [
	"loading_sprite_27.png",
	"assets/Microsoft OneNote2.png",
	"level_spell_arena_tex_.png",
	"assets/NewSprite13.png",
	"Layer 2.png",
	"Layer 3.png",
	"Layer 4.png",
	"Layer 5.png",
	"chr_skeleton_sprite_064.png",
	"chr_skeleton_sprite_065.png",
	"chr_skeleton_sprite_066.png",
	"chr_skeleton_sprite_067.png",
	"chr_skeleton_sprite_068.png",
	"chr_skeleton_sprite_069.png",
	"chr_skeleton_sprite_070.png",
	"chr_skeleton_sprite_071.png",
	"chr_skeleton_sprite_000.png",
	"chr_skeleton_sprite_001.png",
	"chr_skeleton_sprite_002.png",
	"chr_skeleton_sprite_003.png",
	"chr_skeleton_sprite_004.png",
	"chr_skeleton_sprite_005.png",
	"chr_skeleton_sprite_006.png",
	"chr_skeleton_sprite_007.png",
	"chr_skeleton_sprite_032.png",
	"chr_skeleton_sprite_033.png",
	"chr_skeleton_sprite_034.png",
	"chr_skeleton_sprite_035.png",
	"chr_skeleton_sprite_036.png",
	"chr_skeleton_sprite_037.png",
	"chr_skeleton_sprite_038.png",
	"chr_skeleton_sprite_039.png",
	"chr_skeleton_sprite_056.png",
	"chr_skeleton_sprite_057.png",
	"chr_skeleton_sprite_058.png",
	"chr_skeleton_sprite_059.png",
	"chr_skeleton_sprite_060.png",
	"chr_skeleton_sprite_061.png",
	"chr_skeleton_sprite_062.png",
	"chr_skeleton_sprite_063.png",
	"chr_skeleton_sprite_008.png",
	"chr_skeleton_sprite_009.png",
	"chr_skeleton_sprite_010.png",
	"chr_skeleton_sprite_011.png",
	"chr_skeleton_sprite_012.png",
	"chr_skeleton_sprite_013.png",
	"chr_skeleton_sprite_014.png",
	"chr_skeleton_sprite_015.png",
	"assets/NewSprite14.png",
	"assets/tutorial_sprite_04.png",
	"assets/chr_princess_sprite_000.png",
	"assets/chr_princess_sprite_504.png",
	"iexf6dq1okef1.png",
	"ui_sprite_159.png",
	"ui_sprite_187.png",
	"ui_sprite_188.png",
	"ui_sprite_160.png",
	"ui_sprite_252.png",
	"iexf6dq1okef1 (1).png",
	"iexf6dq1okef1 (2).png",
	"iexf6dq1okef1 (6).png",
	"iexf6dq1okef1 (3).png",
	"iexf6dq1okef1 (4).png",
	"iexf6dq1okef1 (5).png",
	"iexf6dq1okef1 (7).png",
	"iexf6dq1okef1 (8).png",
	"iexf6dq1okef1 (9).png",
	"iexf6dq1okef2.png",
	"iexf6dq1okef1 (10).png",
	"frames_0035-1.png.png",
	"chr_skeleton_sprite_081.png",
	"chr_skeleton_sprite_082.png",
	"chr_skeleton_sprite_083.png",
	"chr_skeleton_sprite_084.png",
	"chr_skeleton_sprite_089.png",
	"chr_skeleton_sprite_090.png",
	"chr_skeleton_sprite_091.png",
	"chr_skeleton_sprite_092.png",
	"chr_skeleton_sprite_097.png",
	"chr_skeleton_sprite_098.png",
	"chr_skeleton_sprite_099.png",
	"chr_skeleton_sprite_100.png",
	"chr_skeleton_sprite_113.png",
	"chr_skeleton_sprite_114.png",
	"chr_skeleton_sprite_115.png",
	"chr_skeleton_sprite_116.png",
	"chr_skeleton_sprite_109.png",
	"chr_skeleton_sprite_110.png",
	"chr_skeleton_sprite_111.png",
	"chr_skeleton_sprite_112.png",
	"ui_sprite_207.png",
	"ui_sprite_253.png",
	"assets/ui_sprite_255.png",
	"assets/ui_sprite_257.png",
	"assets/ui_sprite_254.png",
	"l1_sprite_001.png",
	"l0_sprite_003.png",
	"l0_sprite_010.png",
	"l0_sprite_021.png",
	"l0_sprite_030.png",
	"l0_sprite_040.png",
	"l0_sprite_043.png",
	"l0_sprite_047.png",
	"l0_sprite_055.png",
	"l0_sprite_115.png",
	"l0_sprite_121.png",
	"assets/ui_sprite_253.png",
	"assets/128.png",
	"assets/129.png",
	"assets/130.png",
	"assets/131.png",
	"assets/132.png",
	"assets/133.png",
	"assets/134.png",
	"assets/135.png",
	"assets/136.png",
	"assets/137.png",
	"assets/138.png",
	"assets/139.png",
	"assets/140.png",
	"assets/141.png",
	"assets/142.png",
	"assets/143.png",
	"assets/144.png",
	"assets/145.png",
	"assets/146.png",
	"assets/147.png",
	"assets/148.png",
	"assets/149.png",
	"assets/150.png",
	"assets/151.png",
	"assets/152.png",
	"assets/153.png",
	"assets/154.png",
	"assets/155.png",
	"assets/156.png",
	"assets/157.png",
	"assets/158.png",
	"assets/159.png",
	"assets/160.png",
	"assets/161.png",
	"assets/162.png",
	"assets/163.png",
	"assets/164.png",
	"assets/165.png",
	"assets/166.png",
	"assets/167.png",
	"assets/168.png",
	"assets/169.png",
	"assets/170.png",
	"assets/171.png",
	"assets/172.png",
	"assets/173.png",
	"assets/174.png",
	"assets/175.png",
	"assets/176.png",
	"assets/177.png",
	"assets/178.png",
	"assets/179.png",
	"assets/180.png",
	"assets/181.png",
	"assets/182.png",
	"assets/183.png",
	"assets/184.png",
	"assets/185.png",
	"assets/186.png",
	"assets/187.png",
	"assets/188.png",
	"assets/189.png",
	"assets/190.png",
	"assets/191.png",
	"assets/192.png",
	"assets/193.png",
	"assets/194.png",
	"assets/195.png",
	"assets/196.png",
	"assets/197.png",
	"assets/198.png",
	"assets/199.png",
	"assets/200.png",
	"assets/201.png",
	"assets/202.png",
	"assets/203.png",
	"assets/204.png",
	"assets/205.png",
	"assets/206.png",
	"assets/207.png",
	"assets/208.png",
	"assets/209.png",
	"assets/210.png",
	"assets/211.png",
	"assets/212.png",
	"assets/213.png",
	"assets/214.png",
	"assets/215.png",
	"assets/216.png",
	"assets/217.png",
	"assets/218.png",
	"assets/219.png",
	"assets/220.png",
	"assets/221.png",
	"assets/222.png",
	"assets/223.png",
	"assets/224.png",
	"assets/225.png",
	"assets/226.png",
	"assets/227.png",
	"assets/228.png",
	"assets/229.png",
	"assets/230.png",
	"assets/231.png",
	"assets/232.png",
	"assets/233.png",
	"assets/234.png",
	"assets/235.png",
	"assets/236.png",
	"assets/237.png",
	"assets/238.png",
	"assets/239.png",
	"assets/240.png",
	"assets/241.png",
	"assets/242.png",
	"assets/243.png",
	"assets/244.png",
	"assets/245.png",
	"assets/246.png",
	"assets/247.png",
	"assets/248.png",
	"assets/249.png",
	"assets/250.png",
	"assets/251.png",
	"assets/252.png",
	"assets/253.png",
	"assets/254.png",
	"assets/255.png",
	"assets/256.png",
	"assets/257.png",
	"assets/258.png",
	"assets/259.png",
	"assets/260.png",
	"assets/261.png",
	"assets/262.png",
	"assets/263.png",
	"assets/264.png",
	"assets/265.png",
	"assets/266.png",
	"assets/267.png",
	"assets/268.png",
	"assets/269.png",
	"assets/270.png",
	"assets/271.png",
	"assets/272.png",
	"assets/273.png",
	"assets/274.png",
	"assets/275.png",
	"assets/276.png",
	"assets/277.png",
	"assets/278.png",
	"assets/279.png",
	"assets/280.png",
	"assets/281.png",
	"assets/282.png",
	"assets/283.png",
	"assets/284.png",
	"assets/285.png",
	"assets/286.png",
	"assets/287.png",
	"assets/288.png",
	"assets/289.png",
	"assets/290.png",
	"assets/291.png",
	"assets/292.png",
	"assets/293.png",
	"assets/294.png",
	"assets/295.png",
	"assets/296.png",
	"assets/297.png",
	"assets/298.png",
	"assets/299.png",
	"assets/300.png",
	"assets/301.png",
	"assets/302.png",
	"assets/303.png",
	"assets/304.png",
	"assets/305.png",
	"assets/306.png",
	"assets/307.png",
	"assets/308.png",
	"assets/309.png",
	"sprite_003.png",
	"sprite_014.png",
	"sprite_015.png",
	"sprite_016.png",
	"sprite_017.png",
	"sprite_018.png",
	"sprite_019.png",
	"sprite_020.png",
	"sprite_021.png",
	"sprite_005.png",
	"sprite_024.png",
	"sprite_025.png",
	"sprite_026.png",
	"sprite_027.png",
	"sprite_028.png",
	"sprite_029.png",
	"sprite_030.png",
	"sprite_031.png",
	"sprite_032.png",
	"frames_0026.png",
	"assets/NewSprite255.png",
	"assets/UI.png",
	"assets\\UI.png",
	"assets/UI4.png",
	"assets\\UI4.png",
	"assets/blue_90.png",
	"assets/blue_91.png",
	"assets/UI5.png",
	"assets\\UI5.png",
	"assets/UI6.png",
	"assets\\UI6.png",
	"assets/UI7.png",
	"assets\\UI7.png",
	"assets/UI8.png",
	"assets\\UI8.png",
	"assets/UI9.png",
	"assets\\UI9.png",
	"assets/UI10.png",
	"assets\\UI10.png",
	"assets/blue_80.png",
	"assets/blue_81.png",
	"assets/blue_70.png",
	"assets/blue_60.png",
	"assets/blue_50.png",
	"assets/blue_40.png",
	"assets/blue_30.png",
	"assets/blue_20.png",
	"assets/blue_10.png",
	"assets/red.png",
	"assets\\red.png",
	"assets/red2.png",
	"assets\\red2.png",
	"assets/white2.png",
	"assets\\white2.png",
	"assets/red4.png",
	"assets\\red4.png",
	"assets/white3.png",
	"assets\\white3.png",
	"assets/red3.png",
	"assets\\red3.png",
	"assets/white4.png",
	"assets\\white4.png",
	"assets/white7.png",
	"assets\\white7.png",
	"assets/white8.png",
	"assets\\white8.png",
	"assets/white10.png",
	"assets\\white10.png",
	"assets/white9.png",
	"assets\\white9.png",
	"assets/white6.png",
	"assets\\white6.png",
	"assets/white5.png",
	"assets\\white5.png",
	"assets/red5.png",
	"assets\\red5.png",
	"assets/red6.png",
	"assets\\red6.png",
	"assets/red7.png",
	"assets\\red7.png",
	"assets/red8.png",
	"assets\\red8.png",
	"assets/red9.png",
	"assets\\red9.png",
	"assets/red10.png",
	"assets\\red10.png",
	"fontbolt (1).png",
	"fontbolt.png",
	"frames_0106.png",
	"assets/building_tower_sprite_016.png",
	"assets/building_tower_sprite_017.png",
	"assets/building_tower_sprite_018.png",
	"assets/building_tower_sprite_019.png",
	"assets/building_tower_sprite_020.png",
	"assets/building_tower_sprite_021.png",
	"assets/building_tower_sprite_022.png",
	"assets/building_tower_sprite_023.png",
	"assets/building_tower_sprite_024.png",
	"assets/building_tower_sprite_025.png",
	"assets/building_tower_sprite_026.png",
	"assets/building_tower_sprite_027.png",
	"assets/building_tower_sprite_028.png",
	"assets/building_tower_sprite_101.png",
	"assets/building_tower_sprite_102.png",
	"assets/building_tower_sprite_103.png",
	"assets/building_tower_sprite_104.png",
	"assets/building_tower_sprite_105.png",
	"assets/building_tower_sprite_106.png",
	"assets/building_tower_sprite_107.png",
	"assets/building_tower_sprite_108.png",
	"assets/building_tower_sprite_109.png",
	"assets/building_tower_sprite_110.png",
	"assets/building_tower_sprite_111.png",
	"assets/building_tower_sprite_112.png",
	"assets/building_tower_sprite_113.png",
	"assets/assets_StarterPushable.png",
	"output.png",
	"clashroyale3.png",
	"Layer3.png",
	"sss0.png",
	"sss1.png",
	"sss2.png",
	"effects_sprite_067.png",
	"effects_sprite_068.png",
	"effects_sprite_069.png",
	"effects_sprite_066.png",
	"effects_sprite_070.png",
	"effects_sprite_071.png",
	"effects_sprite_072.png",
	"effects_sprite_073.png",
	"effects_sprite_074.png",
	"ui_sprite_072.png",
	"ui_sprite_154.png",
	"ui_sprite_184.png",
	"Layer 1 copy 2.png",
	"Layer 1 copy.png",
	"Background copy 2.png",
	"Background copy.png",
	"Layer 1 copy4.png",
	"Layer 1 copy5.png",
	"assets/effects_sprite_067.png",
	"assets/effects_sprite_068.png",
	"assets/effects_sprite_069.png",
	"assets/effects_sprite_070.png",
	"assets/effects_sprite_071.png",
	"assets/effects_sprite_072.png",
	"assets/effects_sprite_073.png",
	"assets/effects_sprite_074.png",
	"assets/effects_sprite_075.png",
	"assets/effects_sprite_076.png",
	"assets/effects_sprite_077.png",
	"assets/effects_sprite_078.png",
	"level_spell_arena_tex_2.png",
	"timerbg.png",
	"ui_sprite_201.png",
	"assets/ui_sprite_259.png",
	"assets/NewSprite50.png",
	"assets/NewSprite51.png",
	"assets/NewSprite52.png",
	"assets/NewSprite53.png",
	"assets/NewSprite54.png",
	"assets/NewSprite55.png",
	"assets/NewSprite56.png",
	"assets/NewSprite57.png",
	"assets/NewSprite58.png",
	"assets/NewSprite59.png",
	"assets/NewSprite60.png",
	"assets/NewSprite61.png",
	"assets/NewSprite62.png",
	"assets/NewSprite63.png",
	"assets/NewSprite64.png",
	"assets/NewSprite65.png",
	"assets/NewSprite66.png",
	"assets/NewSprite67.png",
	"assets/NewSprite68.png",
	"assets/NewSprite69.png",
	"assets/NewSprite70.png",
	"assets/NewSprite71.png",
	"assets/NewSprite72.png",
	"assets/NewSprite73.png",
	"assets/NewSprite74.png",
	"assets/NewSprite75.png",
	"assets/NewSprite76.png",
	"assets/NewSprite77.png",
	"assets/NewSprite78.png",
	"assets/NewSprite79.png",
	"assets/NewSprite80.png",
	"assets/NewSprite81.png",
	"assets/NewSprite82.png",
	"assets/NewSprite83.png",
	"assets/NewSprite84.png",
	"assets/NewSprite85.png",
	"assets/NewSprite86.png",
	"assets/NewSprite87.png",
	"assets/NewSprite88.png",
	"assets/NewSprite89.png",
	"assets/NewSprite90.png",
	"assets/effects_sprite_079.png",
	"assets/effects_sprite_080.png",
	"assets/effects_sprite_081.png",
	"assets/effects_sprite_082.png",
	"assets/effects_sprite_083.png",
	"assets/effects_sprite_084.png",
	"assets/effects_sprite_085.png",
	"assets/effects_sprite_086.png",
	"assets/effects_sprite_087.png",
	"assets/effects_sprite_088.png",
	"assets/effects_sprite_089.png",
	"assets/effects_sprite_090.png",
	"assets/DarkMagicSmoke.png",
	"DarkMagicSmoke.png",
	"effects_sprite_076.png",
	"effects_sprite_063.png",
	"effects_sprite_064.png",
	"effects_sprite_065.png",
	"effects_sprite_088.png",
	"effects_sprite_077.png",
	"effects_sprite_022.png",
	"effects_sprite_022 copy.png",
	"effects_sprite_022 copy2.png",
	"assets/NewSprite91.png",
	"effects_sprite_141.png",
	"effects_sprite_142.png",
	"effects_sprite_143.png",
	"effects_sprite_144.png",
	"image67.png",
	"image68.png",
	"image69.png",
	"image70.png",
	"image71.png",
	"image72.png",
	"image73.png",
	"image74.png",
	"image75.png",
	"image76.png",
	"image77.png",
	"image78.png",
	"image79.png",
	"image80.png",
	"image81.png",
	"image82.png",
	"image83.png",
	"image84.png",
	"image85.png",
	"image86.png",
	"image87.png",
	"image88.png",
	"image89.png",
	"image90.png",
	"image91.png",
	"image92.png",
	"image93.png",
	"image94.png",
	"image95.png",
	"image96.png",
	"image97.png",
	"image98.png",
	"image99.png",
	"image100.png",
	"image101.png",
	"image102.png",
	"image103.png",
	"image104.png",
	"image105.png",
	"image106.png",
	"image107.png",
	"image108.png",
	"image109.png",
	"image110.png",
	"image111.png",
	"image112.png",
	"image113.png",
	"image114.png",
	"image115.png",
	"image116.png",
	"image117.png",
	"image118.png",
	"image119.png",
	"image120.png",
	"image121.png",
	"image122.png",
	"image123.png",
	"image124.png",
	"image125.png",
	"image126.png",
	"image127.png",
	"image128.png",
	"image129.png",
	"image130.png",
	"image131.png",
	"image132.png",
	"image133.png",
	"image134.png",
	"image135.png",
	"image136.png",
	"image137.png",
	"image138.png",
	"image139.png",
	"image140.png",
	"image141.png",
	"image142.png",
	"image143.png",
	"image144.png",
	"image145.png",
	"image146.png",
	"image147.png",
	"image148.png",
	"image149.png",
	"image150.png",
	"image151.png",
	"image152.png",
	"image153.png",
	"image154.png",
	"image155.png",
	"image156.png",
	"image157.png",
	"image158.png",
	"image159.png",
	"image160.png",
	"image161.png",
	"image162.png",
	"image163.png",
	"image164.png",
	"image165.png",
	"image166.png",
	"image167.png",
	"image168.png",
	"image169.png",
	"image170.png",
	"image171.png",
	"image172.png",
	"image173.png",
	"image174.png",
	"image175.png",
	"image176.png",
	"image177.png",
	"image178.png",
	"image179.png",
	"image180.png",
	"image181.png",
	"image182.png",
	"image183.png",
	"image184.png",
	"image185.png",
	"image186.png",
	"image187.png",
	"image188.png",
	"image189.png",
	"image190.png",
	"image191.png",
	"image192.png",
	"image193.png",
	"image194.png",
	"image195.png",
	"image196.png",
	"image197.png",
	"image198.png",
	"image199.png",
	"image200.png",
	"image201.png",
	"image202.png",
	"image203.png",
	"image204.png",
	"image205.png",
	"image206.png",
	"image207.png",
	"image208.png",
	"image209.png",
	"image210.png",
	"image211.png",
	"image212.png",
	"image213.png",
	"image214.png",
	"image215.png",
	"image216.png",
	"image217.png",
	"image218.png",
	"image219.png",
	"image220.png",
	"image221.png",
	"image222.png",
	"image223.png",
	"_a_effects_sprite_080.png",
	"_a_effects_sprite_081.png",
	"_a_effects_sprite_082.png",
	"_a_effects_sprite_083.png",
	"_a_effects_sprite_084.png",
	"_a_effects_sprite_085.png",
	"_a_effects_sprite_086.png",
	"_a_effects_sprite_087.png",
	"_a_effects_sprite_089.png",
	"_a_effects_sprite_090.png",
	"_a_effects_sprite_091.png",
	"_a_effects_sprite_092.png",
	"_a_effects_sprite_093.png",
	"_a_effects_sprite_094.png",
	"_a_effects_sprite_095.png",
	"_a_effects_sprite_096.png",
	"assets/effects_sprite_253.png2.png",
	"building_tower_sprite_205.png",
	"Folder 3.png",
	"Folder 4.png",
	"Folder 5.png",
	"Folder3.png",
	"effects_sprite_079.png",
	"Layer 1 (1).png",
	"crownblack.png",
	"cardholder2.png",
	"Folder 1.png",
	"Layer2.png",
	"goodgame.png",
	"goodluck2.png",
	"oops2.png",
	"thanks2.png",
	"well_played2.png",
	"wow2.png",
	"Folder2.png",
	"assets/NewSprite92.png",
	"frame_0097.png",
	"anger.png",
	"cry.png",
	"laugh.png",
	"thumbsup.png",
	"Layer 2 (2).png",
	"frame_0098.png",
	"cardholder3.png",
	"assets/EmotesIcon.png",
	"assets/EmotesIcon2.png",
	"assets/EmotesIcon3.png",
	"assets/EmotesIcon4.png",
	"assets/EmotesIcon5.png",
	"assets/EmotesIcon6.png",
	"assets/EmotesIcon7.png",
	"assets/EmotesIcon8.png",
	"assets/EmotesIcon9.png",
	"assets/EmotesIcon10.png",
	"assets/EmotesIcon11.png",
	"assets/EmotesIcon12.png",
	"assets/EmotesIcon13.png",
	"assets/EmotesIcon14.png",
	"assets/EmotesIcon15.png",
	"assets/EmotesIcon16.png",
	"assets/EmotesIcon17.png",
	"assets/EmotesIcon18.png",
	"assets/EmotesIcon19.png",
	"assets/EmotesIcon20.png",
	"assets/EmotesIcon21.png",
	"assets/EmotesIcon22.png",
	"assets/EmotesIcon23.png",
	"assets/EmotesIcon24.png",
	"assets/EmotesIcon25.png",
	"assets/EmotesIcon26.png",
	"assets/EmotesIcon27.png",
	"assets/EmotesIcon28.png",
	"assets/EmotesIcon29.png",
	"assets/EmotesIcon30.png",
	"assets/EmotesIcon31.png",
	"assets/EmotesIcon32.png",
	"assets/EmotesIcon33.png",
	"assets/EmotesIcon34.png",
	"assets/EmotesIcon35.png",
	"assets/EmotesIcon36.png",
	"assets/EmotesIcon37.png",
	"assets/EmotesIcon38.png",
	"assets/EmotesIcon39.png",
	"assets/EmotesIcon40.png",
	"assets/EmotesIcon41.png",
	"assets/EmotesIcon42.png",
	"assets/EmotesIcon43.png",
	"assets/EmotesIcon44.png",
	"assets/EmotesIcon45.png",
	"assets/EmotesIcon46.png",
	"assets/EmotesIcon47.png",
	"assets/EmotesIcon48.png",
	"assets/EmotesIcon49.png",
	"assets/EmotesIcon50.png",
	"assets/EmotesIcon51.png",
	"assets/EmotesIcon52.png",
	"assets/EmotesIcon53.png",
	"assets/EmotesIcon54.png",
	"assets/EmotesIcon55.png",
	"assets/EmotesIcon56.png",
	"assets/EmotesIcon57.png",
	"assets/EmotesIcon58.png",
	"assets/EmotesIcon59.png",
	"assets/EmotesIcon60.png",
	"assets/EmotesIcon61.png",
	"assets/EmotesIcon62.png",
	"assets/EmotesIcon63.png",
	"assets/EmotesIcon64.png",
	"assets/EmotesIcon65.png",
	"assets/EmotesIcon66.png",
	"assets/EmotesIcon67.png",
	"assets/EmotesIcon68.png",
	"assets/EmotesIcon69.png",
	"assets/EmotesIcon70.png",
	"assets/EmotesIcon71.png",
	"goodgame2.png",
	"goodluck3.png",
	"oops3.png",
	"thanks3.png",
	"well_played3.png",
	"wow3.png",
	"goodgame3.png",
	"goodluck4.png",
	"oops4.png",
	"thanks4.png",
	"well_played4.png",
	"wow4.png",
	"assets/NewSprite93.png",
	"assets/NewSprite94.png",
	"assets/NewSprite95.png",
	"assets/NewSprite96.png",
	"assets/NewSprite97.png",
	"assets/NewSprite98.png",
	"assets/NewSprite99.png",
	"assets/NewSprite100.png",
	"assets/NewSprite101.png",
	"assets/NewSprite102.png",
	"assets/NewSprite103.png",
	"assets/NewSprite104.png",
	"assets/NewSprite105.png",
	"assets/NewSprite106.png",
	"assets/NewSprite107.png",
	"assets/NewSprite108.png",
	"assets/NewSprite109.png",
	"assets/NewSprite110.png",
	"assets/NewSprite111.png",
	"assets/NewSprite112.png",
	"assets/NewSprite113.png",
	"assets/NewSprite114.png",
	"assets/NewSprite115.png",
	"assets/NewSprite116.png",
	"assets/NewSprite117.png",
	"assets/NewSprite118.png",
	"assets/NewSprite119.png",
	"assets/NewSprite120.png",
	"Clash-Regular.png",
	"CalciFurnaceBG.png",
	"FireFurnaceBG.png",
	"FurnaceWalkBG.png",
	"LavaLampBG.png",
	"Shape3.png",
	"assets/NewSprite23.png",
	"assets/NewSprite24.png",
	"assets/NewSprite25.png",
	"assets/NewSprite26.png",
	"assets/NewSprite27.png",
	"assets/NewSprite28.png",
	"assets/NewSprite29.png",
	"assets/NewSprite30.png",
	"assets/NewSprite31.png",
	"assets/NewSprite32.png",
	"assets/NewSprite33.png",
	"assets/NewSprite34.png",
	"assets/NewSprite43.png",
	"assets/NewSprite44.png",
	"assets/NewSprite45.png",
	"assets/NewSprite46.png",
	"assets/NewSprite47.png",
	"assets/NewSprite48.png",
	"assets/NewSprite49.png",
	"assets/NewSprite121.png",
	"assets/NewSprite122.png",
	"assets/NewSprite123.png",
	"assets/BannerBackground.png",
	"button.png",
	"ui-tex-1.png",
	"ui_sprite_226.png",
	"ui_sprite_260.png",
	"ui_sprite_280.png",
	"ui_sprite_446.png",
	"ui_sprite_503.png",
	"ui_sprite_539.png",
	"ui_sprite_564.png",
	"ui_sprite_610.png",
	"ui_sprite_861.png",
	"ui_sprite_598.png",
	"barrel.png",
	"boat.png",
	"castle.png",
	"china.png",
	"electro.png",
	"lantern.png",
	"lava.png",
	"legendary.png",
	"magic.png",
	"pvp.png",
	"snow.png",
	"tiki.png",
	"treehouse.png",
	"tutorial.png",
	"undead.png",
	"well.png",
	"dwqee.png",
	"assets/ui_sprite_518.png3.png",
	"assets/ui_sprite_517.png3.png",
	"assets/loading_sprite_32.png",
	"assets/loading_sprite_00.png",
	"assets/button.png2.png",
	"assets/ui_arena_sprite_005.png",
	"ui_sprite_240.png",
	"assets/ui_sprite_239.png",
	"ui_sprite_210.png",
	"ui_sprite_211.png",
	"ui_sprite_212.png",
	"ui_sprite_213.png",
	"ui_sprite_214.png",
	"ui_sprite_215.png",
	"ui_sprite_216.png",
	"ui_sprite_217.png",
	"ui_sprite_218.png",
	"ui_sprite_219.png",
	"ui_sprite_220.png",
	"ui_sprite_221.png",
	"ui_sprite_228.png",
	"ui_sprite_229.png",
	"ui_sprite_230.png",
	"ui_sprite_231.png",
	"ui_sprite_232.png",
	"ui_sprite_233.png",
	"ui_sprite_234.png",
	"ui_sprite_235.png",
	"ui_sprite_236.png",
	"ui_sprite_237.png",
	"ui_sprite_238.png",
	"ui_sprite_752.png",
	"ui_sprite_753.png",
	"ui_sprite_754.png",
	"ui_sprite_755.png",
	"ui_sprite_756.png",
	"ui_sprite_757.png",
	"ui_sprite_758.png",
	"ui_sprite_759.png",
	"ui_sprite_760.png",
	"ui_sprite_761.png",
	"ui_sprite_762.png",
	"ui_sprite_763.png",
	"ui_sprite_705.png",
	"ui_sprite_706.png",
	"ui_sprite_707.png",
	"ui_sprite_708.png",
	"ui_sprite_709.png",
	"ui_sprite_710.png",
	"ui_sprite_711.png",
	"ui_sprite_712.png",
	"ui_sprite_713.png",
	"ui_sprite_714.png",
	"ui_sprite_715.png",
	"ui_sprite_716.png",
	"ui_sprite_717.png",
	"ui_sprite_718.png",
	"ui_sprite_719.png",
	"ui_sprite_720.png",
	"ui_sprite_721.png",
	"ui_sprite_722.png",
	"ui_sprite_723.png",
	"ui_sprite_724.png",
	"ui_sprite_725.png",
	"ui_sprite_726.png",
	"ui_sprite_727.png",
	"ui_sprite_339.png",
	"ui_sprite_342.png",
	"ui_sprite_321.png",
	"plus.png",
	"ui_sprite_477.png",
	"assets/logo.png",
	"assets/logo2.png",
	"assets/logo3.png",
	"assets/logo4.png",
	"assets/logo5.png",
	"assets/logo6.png",
	"assets/logo7.png",
	"assets/logo8.png",
	"assets/logo9.png",
	"assets/logo10.png",
	"assets/logo11.png",
	"assets/logo12.png",
	"assets/logo13.png",
	"assets/logo14.png",
	"assets/logo15.png",
	"assets/logo16.png",
	"assets/logo17.png",
	"assets/logo18.png",
	"assets/logo19.png",
	"assets/logo20.png",
	"assets/logo21.png",
	"assets/logo22.png",
	"assets/logo23.png",
	"assets/logo24.png",
	"assets/logo25.png",
	"assets/logo26.png",
	"assets/logo27.png",
	"assets/logo28.png",
	"assets/logo29.png",
	"assets/logo30.png",
	"assets/logo31.png",
	"assets/logo32.png",
	"assets/logo33.png",
	"assets/logo34.png",
	"assets/logo35.png",
	"assets/logo36.png",
	"assets/logo37.png",
	"assets/logo38.png",
	"assets/logo39.png",
	"assets/logo40.png",
	"assets/logo41.png",
	"assets/logo42.png",
	"assets/logo43.png",
	"assets/logo44.png",
	"assets/logo45.png",
	"assets/logo46.png",
	"assets/logo47.png",
	"assets/logo48.png",
	"assets/logo49.png",
	"assets/logo50.png",
	"assets/logo51.png",
	"assets/logo52.png",
	"assets/logo53.png",
	"assets/logo54.png",
	"assets/logo55.png",
	"assets/logo56.png",
	"assets/logo57.png",
	"assets/logo58.png",
	"assets/logo59.png",
	"assets/logo60.png",
	"assets/logo61.png",
	"assets/logo62.png",
	"assets/logo63.png",
	"assets/logo64.png",
	"assets/logo65.png",
	"assets/logo66.png",
	"assets/logo67.png",
	"assets/logo68.png",
	"assets/logo69.png",
	"assets/logo70.png",
	"assets/logo71.png",
	"assets/logo72.png",
	"assets/logo73.png",
	"assets/logo74.png",
	"assets/logo75.png",
	"assets/logo76.png",
	"assets/logo77.png",
	"assets/logo78.png",
	"assets/logo79.png",
	"assets/logo80.png",
	"assets/logo81.png",
	"assets/logo82.png",
	"assets/logo83.png",
	"assets/logo84.png",
	"assets/logo85.png",
	"assets/logo86.png",
	"assets/logo87.png",
	"assets/logo88.png",
	"assets/logo89.png",
	"assets/logo90.png",
	"assets/logo91.png",
	"assets/logo92.png",
	"assets/logo93.png",
	"assets/logo94.png",
	"assets/logo95.png",
	"assets/logo96.png",
	"assets/logo97.png",
	"assets/logo98.png",
	"assets/logo99.png",
	"assets/logo100.png",
	"assets/logo101.png",
	"assets/logo102.png",
	"assets/logo103.png",
	"assets/logo104.png",
	"assets/logo105.png",
	"assets/logo106.png",
	"assets/logo107.png",
	"assets/logo108.png",
	"assets/logo109.png",
	"assets/logo110.png",
	"assets/logo111.png",
	"assets/logo112.png",
	"assets/logo113.png",
	"assets/logo114.png",
	"assets/logo115.png",
	"assets/logo116.png",
	"assets/logo117.png",
	"assets\\logo96.png",
	"ui_sprite_520.png",
	"Folder4.png",
	"ui_sprite_279.png",
	"ui_sprite_284.png",
	"ui_sprite_334 copy.png",
	"ui_sprite_174.png",
	"ui_sprite_189.png",
	"ui_sprite_557.png",
	"ui_sprite_521.png",
	"icon.png",
	"assets/desktop-icon-512.png",
	"desktop-icon-512.png",
	"assets/android-icon-192.png",
	"android-icon-192.png",
	"assets/android-icon-144.png",
	"android-icon-144.png",
	"assets/android-icon-96.png",
	"android-icon-96.png",
	"assets/android-icon-72.png",
	"android-icon-72.png",
	"assets/android-icon-48.png",
	"android-icon-48.png",
	"assets/android-icon-36.png",
	"android-icon-36.png",
	"assets/android-windowSplashScreenAnimatedIcon.png",
	"android-windowSplashScreenAnimatedIcon.png",
	"assets/ios-icon-1024.png",
	"ios-icon-1024.png",
	"assets/ios-icon-180.png",
	"ios-icon-180.png",
	"assets/ios-icon-167.png",
	"ios-icon-167.png",
	"assets/ios-icon-152.png",
	"ios-icon-152.png",
	"assets/ios-icon-144.png",
	"ios-icon-144.png",
	"assets/ios-icon-120.png",
	"ios-icon-120.png",
	"assets/ios-icon-114.png",
	"ios-icon-114.png",
	"assets/ios-icon-100.png",
	"ios-icon-100.png",
	"assets/ios-icon-87.png",
	"ios-icon-87.png",
	"assets/ios-icon-80.png",
	"ios-icon-80.png",
	"assets/ios-icon-76.png",
	"ios-icon-76.png",
	"assets/ios-icon-72.png",
	"ios-icon-72.png",
	"assets/ios-icon-60.png",
	"ios-icon-60.png",
	"assets/ios-icon-58.png",
	"ios-icon-58.png",
	"assets/ios-icon-57.png",
	"ios-icon-57.png",
	"assets/ios-icon-50.png",
	"ios-icon-50.png",
	"assets/ios-icon-40.png",
	"ios-icon-40.png",
	"assets/ios-icon-29.png",
	"ios-icon-29.png",
	"assets/ios-icon-20.png",
	"ios-icon-20.png",
];


function preloadImagesWithProgress(urls) {
  let loadedCount = 0;
  const totalCount = urls.length;

  // Initial safety check
  if (totalCount === 0) {
    loadingBar.setNumber(100);
    return Promise.resolve([]);
  }

  // Map each URL to a promise
  const promises = urls.map(url => {
    return new Promise((resolve) => {
      const img = new Image();
      img.src = url;

      // Create a unified callback for success or failure
      const handleImageLoad = () => {
        loadedCount++;
        // Calculate percentage (0 to 100)
        const percentage = Math.round((loadedCount / totalCount) * 100);
        
        // Update your loading bar
        loadingBar.setNumber(percentage); 
        
        resolve(img);
      };

      img.onload = handleImageLoad;
      
      // Using onerror ensures the bar doesn't freeze if one image fails
      img.onerror = handleImageLoad; 
    });
  });

  // Return a promise that resolves when everything is processed
  return Promise.all(promises);
}

// Usage
preloadImagesWithProgress(imageURLs)
  .then(() => {
    console.log("Preloading complete. Progress bar is at 100%.");
    // Start your game, reveal your gallery, or hide the loading overlay here
  });
};
gdjs.LoadingCode.eventsList0 = function(runtimeScene) {

{

gdjs.copyArray(runtimeScene.getObjects("LoadingBar"), gdjs.LoadingCode.GDLoadingBarObjects1);

const objects = gdjs.LoadingCode.GDLoadingBarObjects1;
gdjs.LoadingCode.userFunc0x1a244b0(runtimeScene, objects);

}


};gdjs.LoadingCode.eventsList1 = function(runtimeScene) {

{


let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.runtimeScene.sceneJustBegins(runtimeScene);
if (isConditionTrue_0) {
{gdjs.evtTools.sound.playSound(runtimeScene, "sfx\\scroll_loading_01.ogg", false, 100, 1);
}

{ //Subevents
gdjs.LoadingCode.eventsList0(runtimeScene);} //End of subevents
}

}


{


let isConditionTrue_0 = false;
{
gdjs.copyArray(runtimeScene.getObjects("LoadingBar"), gdjs.LoadingCode.GDLoadingBarObjects1);
gdjs.copyArray(runtimeScene.getObjects("LoadingText"), gdjs.LoadingCode.GDLoadingTextObjects1);
{for(var i = 0, len = gdjs.LoadingCode.GDLoadingTextObjects1.length ;i < len;++i) {
    gdjs.LoadingCode.GDLoadingTextObjects1[i].getBehavior("Text").setText(gdjs.evtTools.common.toString(Math.round((( gdjs.LoadingCode.GDLoadingBarObjects1.length === 0 ) ? 0 :gdjs.LoadingCode.GDLoadingBarObjects1[0].Value(null)))) + "%");
}
}
}

}


{


let isConditionTrue_0 = false;
{
gdjs.copyArray(runtimeScene.getObjects("LoadingBar"), gdjs.LoadingCode.GDLoadingBarObjects1);
{for(var i = 0, len = gdjs.LoadingCode.GDLoadingBarObjects1.length ;i < len;++i) {
    gdjs.LoadingCode.GDLoadingBarObjects1[i].SetValue(gdjs.evtTools.common.lerp((gdjs.LoadingCode.GDLoadingBarObjects1[i].Value(null)), runtimeScene.getScene().getVariables().getFromIndex(0).getAsNumber(), 0.025), null);
}
}
}

}


{

gdjs.copyArray(runtimeScene.getObjects("LoadingBar"), gdjs.LoadingCode.GDLoadingBarObjects1);

let isConditionTrue_0 = false;
isConditionTrue_0 = false;
{isConditionTrue_0 = (Math.round((( gdjs.LoadingCode.GDLoadingBarObjects1.length === 0 ) ? 0 :gdjs.LoadingCode.GDLoadingBarObjects1[0].Value(null))) == 100);
}
if (isConditionTrue_0) {
{gdjs.evtTools.runtimeScene.replaceScene(runtimeScene, "Battle", false);
}
}

}


};

gdjs.LoadingCode.func = function(runtimeScene) {
runtimeScene.getOnceTriggers().startNewFrame();

gdjs.LoadingCode.GDBackgroundObjects1.length = 0;
gdjs.LoadingCode.GDBackgroundObjects2.length = 0;
gdjs.LoadingCode.GDlogoObjects1.length = 0;
gdjs.LoadingCode.GDlogoObjects2.length = 0;
gdjs.LoadingCode.GDLoadingBarObjects1.length = 0;
gdjs.LoadingCode.GDLoadingBarObjects2.length = 0;
gdjs.LoadingCode.GDLoadingTextObjects1.length = 0;
gdjs.LoadingCode.GDLoadingTextObjects2.length = 0;
gdjs.LoadingCode.GDLoadingTipObjects1.length = 0;
gdjs.LoadingCode.GDLoadingTipObjects2.length = 0;
gdjs.LoadingCode.GDReplaySpriteObjects1.length = 0;
gdjs.LoadingCode.GDReplaySpriteObjects2.length = 0;

gdjs.LoadingCode.eventsList1(runtimeScene);
gdjs.LoadingCode.GDBackgroundObjects1.length = 0;
gdjs.LoadingCode.GDBackgroundObjects2.length = 0;
gdjs.LoadingCode.GDlogoObjects1.length = 0;
gdjs.LoadingCode.GDlogoObjects2.length = 0;
gdjs.LoadingCode.GDLoadingBarObjects1.length = 0;
gdjs.LoadingCode.GDLoadingBarObjects2.length = 0;
gdjs.LoadingCode.GDLoadingTextObjects1.length = 0;
gdjs.LoadingCode.GDLoadingTextObjects2.length = 0;
gdjs.LoadingCode.GDLoadingTipObjects1.length = 0;
gdjs.LoadingCode.GDLoadingTipObjects2.length = 0;
gdjs.LoadingCode.GDReplaySpriteObjects1.length = 0;
gdjs.LoadingCode.GDReplaySpriteObjects2.length = 0;


return;

}

gdjs['LoadingCode'] = gdjs.LoadingCode;
